#!/bin/bash

green=$(printf '\e[32m')
blue=$(printf '\e[34m')
clear=$(printf '\e[0m')
orange=$(printf '\e[33m')
red=$(printf '\e[31m')
cyan=$(printf '\e[36m')

ColorGreen(){
        echo -ne $green$1$clear
}
ColorBlue(){
        echo -ne $blue$1$clear
}
ColorRed(){
        echo -ne $red$1$clear
}
ColorOrange(){
        echo -ne $orange$1$clear
}
ColorCyan(){
        echo -ne $cyan$1$clear
}
ColorGreen(){
        echo -ne $green$1$clear
}
ColorBlueON(){
        echo -ne $blue
}
ColorRedON(){
        echo -ne $red
}
ColorOrangeON(){
        echo -ne $orange
}
ColorCyanON(){
        echo -ne $cyan
}
ColorClear(){
        echo -ne $clear
}

echo -ne "$(ColorRed '---------------------------------------------------------')\n" 
if ! [ -x "$(command -v openssl)" ] ; then
        echo "The openssl command is required! Please install it and then try again"
        exit 1
fi

if [[ $1 ]]; then
	host $1 > /dev/null
	if [ $? -eq 0 ]; then
		echo -e "$(ColorRed '#') $(ColorGreen 'Checking Domain/Hostname:')\n\t$1"
	else
		echo -e "Error: Could Not Resolve $(ColorGreen ${1}) Domain Name..."
		exit 1
	fi
fi

case $1 in
help)
        echo -ne "Usage:
$(ColorGreen './ssl domain.com')
"
        exit 1
;;
"")
        echo -ne "Usage:
$(ColorGreen './ssl domain.com')
"
        exit 1
;;
*)
	today=$(date +%F)
	expires=$(echo|openssl s_client -servername $1 -connect $1:443 2>/dev/null|openssl x509 -noout -dates|grep 'notAfter'|sed 's/notAfter=//')

	echo -e "$(ColorRed '#') $(ColorGreen 'Leaf Certificate Issued For:')"
	echo|openssl s_client -servername $1 -connect $1:443 2>/dev/null|openssl x509 -noout -subject|sed 's/subject=/Domain: /'
	echo "$(ColorRed '----')"

   echo -e "$(ColorRed '#') $(ColorGreen 'Leaf Certificate Expires In:')"

OS="`uname`"
case $OS in
  'Linux'|'FreeBSD'|'SunOS'|'AIX')
	echo $(( ( $(date -ud "$expires" +'%s') - $(date -ud "$today" +'%s') )/60/60/24 )) days
    ;;
  'Darwin') 
    OS='Mac'
		echo "	$(( ( $(date -j -f "%b %d %T %Y %Z" "$expires" +'%s') - $(date -j -f "%F" "$today" +'%s') )/60/60/24 )) days"
    ;;
  *) 
	echo "Error: Can't Find DATE command for your OS version!"
	;;
esac
	echo "$(ColorRed '----')"
	echo -e "$(ColorRed '#') $(ColorGreen 'Leaf Certificate Dates:')"
	echo|openssl s_client -servername $1 -connect $1:443 2>/dev/null|openssl x509 -noout -dates|\
	 sed 's/notAfter=/Expires On: /' | sed 's/notBefore=/Issued  On: /'
	echo "$(ColorRed '----')"

   echo -e "$(ColorRed '#') $(ColorGreen 'Leaf Certificate Issued by:')"
	echo|openssl s_client -servername $1 -connect $1:443 2>/dev/null|openssl x509 -noout -issuer|sed 's/issuer=/Issuer: /'
	echo "$(ColorRed '----')"

   
	echo -e "$(ColorRed '#') $(ColorGreen 'Leaf Certificate SANs:')"
	echo|openssl s_client -servername $1 -connect $1:443 2>/dev/null|openssl x509 -text |egrep "DNS:"|tr -d " \t"|tr , '\n'|sed  's/^/	/'
	echo "$(ColorRed '----')"

esac
